#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Ilibs -Iinclude
CFLAGS = -Wall -fexceptions
RESINC =
LIBDIR =
LIB =
LDFLAGS = -lSDL2 -lSDL2_image

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c++11
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj
DEP_RELEASE =
OUT_RELEASE = bin/libhitbox.a

INC_EDITOR = $(INC) -Iinclude/editor
CFLAGS_EDITOR = $(CFLAGS) -g
RESINC_EDITOR = $(RESINC)
RCFLAGS_EDITOR = $(RCFLAGS)
LIBDIR_EDITOR = $(LIBDIR)
LIB_EDITOR = $(LIB)-lSDL2_image -lSDL2
LDFLAGS_EDITOR = $(LDFLAGS)
OBJDIR_EDITOR = obj
DEP_EDITOR =
OUT_EDITOR = bin/editor

OBJ_RELEASE = $(OBJDIR_RELEASE)/convex.o $(OBJDIR_RELEASE)/main.o

OBJ_EDITOR = $(OBJDIR_EDITOR)/editor.o $(OBJDIR_EDITOR)/tinyfiledialogs.o $(OBJDIR_EDITOR)/main.o $(OBJDIR_EDITOR)/workspace.o

all: release editor

clean: clean_release clean_editor

before_release:
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: ;

release: before_release out_release after_release ;

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(AR) rcs $(OUT_RELEASE) $(OBJ_RELEASE)

clean_release:
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin
	rm -rf $(OBJDIR_RELEASE)

before_editor:
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_EDITOR) || mkdir -p $(OBJDIR_EDITOR)

after_editor: ;

editor: before_editor out_editor after_editor ;

out_editor: before_editor $(OBJ_EDITOR) $(DEP_EDITOR)
	$(LD) $(LIBDIR_EDITOR) -o $(OUT_EDITOR) $(OBJ_EDITOR)  $(LDFLAGS_EDITOR) $(LIB_EDITOR)

$(OBJDIR_EDITOR)/editor.o: src/editor/editor.cpp
	$(CXX) $(CFLAGS_EDITOR) $(INC_EDITOR) -c src/editor/editor.cpp -o $(OBJDIR_EDITOR)/editor.o

$(OBJDIR_EDITOR)/tinyfiledialogs.o: src/editor/tinyfiledialogs.c
	$(CXX) $(CFLAGS_EDITOR) $(INC_EDITOR) -c src/editor/tinyfiledialogs.c -o $(OBJDIR_EDITOR)/tinyfiledialogs.o

$(OBJDIR_EDITOR)/main.o: src/hitbox/hitbox.cpp
	$(CXX) $(CFLAGS_EDITOR) $(INC_EDITOR) -c src/hitbox/hitbox.cpp -o $(OBJDIR_EDITOR)/main.o

$(OBJDIR_EDITOR)/workspace.o: src/editor/workspace.cpp
	$(CXX) $(CFLAGS_EDITOR) $(INC_EDITOR) -c src/editor/workspace.cpp -o $(OBJDIR_EDITOR)/workspace.o

$(OBJDIR_RELEASE)/convex.o: src/hitbox/convex.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/hitbox/convex.cpp -o $(OBJDIR_RELEASE)/convex.o

clean_editor:
	rm -f $(OBJ_EDITOR) $(OUT_EDITOR)
	rm -rf bin
	rm -rf $(OBJDIR_EDITOR)

.PHONY: before_release after_release clean_release before_editor after_editor clean_editor
